# Generated by Django 4.0.3 on 2022-06-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_food_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='food_items',
        ),
    ]
